refactor: adapt browser & node environments
nervosnetwork/light-godwoken pull request #185
Opened 2022-09-05 02:26 UTC by ShookLyngs

### Description
To publish light-godwoken as an SDK, we need to refactor some parts of it.
In previous version of light-godwoken, we have some codes that can only run on specific envirionment like browser or node:
- Some variables use `process.env.xxx` as their default value, and this is a node specific method
- Some codes use `window.xx` as the value, which is only exist in a browser environment
- The configs of light-godwoken are basically predefined and difficult to customize
- Some features should belong to godwoken-bridge instead of light-godwoken
- Testnet_v0 is deprecated and our test cases are still using the RPC of testnet_v0
- Other issues that rely on the above points

So in this PR, we will basically resolve the above issues by refactoring/fixing the project.

### Light-Godwoken changes
- Organize codes and move them into separate folders
- Replace `window.ethereum` with `EthereumProvider` and refactor relevant codes
- Add `network` param to LightGodwokenProvider and refactor config files for it
- Add `lumosConfig` in LightGodwokenConfig to setup lumos
- Add `getDepositHistories` function to request gwscan api
- Hide testnet_v0 testcases

### Godwoken-Bridge changes
- Move environment variables from light-godwoken to godwoken-bridge
- Move `sudtFaucet` from light-godwoken to godwoken-bridge
- Refactor deposit completed list using gwscan's `deposit_histories` api
- Refactor deposit completed list with ahooks (useInfiniteScroll) for pagination

2022-09-09 09:39 UTC, classicalliu approved these changes

2022-09-09 09:39 UTC, classicalliu commented on packages/light-godwoken/src/config/config.ts
> +    throw new LightGodwokenConfigNotValidError(JSON.stringify(config), "config not valid.");
```suggestion
    throw new LightGodwokenConfigNotValidError(JSON.stringify(config), "invalid config.");
```

2022-09-11 05:10 UTC, Flouse requested changes

2022-09-11 05:10 UTC, Flouse commented on packages/light-godwoken/src/LightGodwokenV0.ts
> +      this.getVersion(),
```suggestion
      "v1",
```

2022-09-11 05:10 UTC, Flouse commented on packages/light-godwoken/src/LightGodwokenV0.ts
> +      this.getVersion(),
I think we should create a v1 provider here.

2022-09-12 05:25 UTC, MrPiNkY2022 reviewed
This is what I was given so can y'all please help me with the project

2022-09-12 11:11 UTC, Flouse commented
> This is what I was given so can y'all please help me with the project

Could you [create an issue](https://github.com/nervosnetwork/light-godwoken/issues/new) to describe what you need?

2022-09-12 14:53 UTC, Flouse approved these changes
LGTM

2022-09-13 03:04 UTC, ShookLyngs commented
To prevent potential issues caused by mixing v0/v1 versions of LightGodwoken, I've added some code to make sure lumos helper functions always use the correct LumosConfig.

2022-09-13 03:11 UTC, merged

2022-09-13 03:27 UTC, RetricSu approved these changes

2022-09-13 03:29 UTC, Flouse commented on packages/light-godwoken/src/__tests__/client.ts
> +export function createLightGodwoken<T extends keyof typeof lightGodwokenVersionMap>(
cc @ShookLyngs

2022-09-13 08:03 UTC, ShookLyngs commented on packages/light-godwoken/src/__tests__/client.ts
> +export function createLightGodwoken<T extends keyof typeof lightGodwokenVersionMap>(
> does this works?

Oh yes it works, this is simpler. I can create PR to fix it afterwards.